spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8
  rabbitmq:
    username: admin
    password: admin
    host: 49.232.243.69
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 49.232.243.69
    database: 0
    port: 6379
  cache:
    cache-names: menus_cache
  flyway:
    baseline-on-migrate: true
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://49.232.243.69/